# DuckDB config reference:
config:
  send_anonymous_usage_stats: False
  use_colors: True
meltano:
  target: "{{ env_var('MELTANO_ENVIRONMENT', 'dev') }}"
  outputs:
    dev:  &dev
      type: duckdb
      path: "{{ env_var('DBT_DUCKDB_PATH') }}"
      threads: 8
      attach:
        # What's going on here: Either MELTANO_PROJECT_READONLY is set by the Dockerfile, in which case we'll use
        # the output directory (which is itself mounted to data/ outside of Docker)...
        # or it's not, in which case we'll use the data directory.
        #
        # The relevant variables are defined either in docker-compose.data_prep.yml or in .vscode/settings.json.
        - path: "{% if env_var('MELTANO_PROJECT_READONLY', 0) == 1 %}\
            {{ env_var('MELTANO_PROJECT_ROOT') }}/output/{{ env_var('TARGET_DUCKDB_FINAL_FILENAME', 'adk_wrapped') }}.db\
            {% else %}\
            {{ env_var('VSCODE_WORKSPACE', '.') }}/data/{{ env_var('TARGET_DUCKDB_FINAL_FILENAME', 'adk_wrapped') }}.db\
            {% endif %}"
          alias: final
    staging:
      <<: *dev
    prod:
      <<: *dev
