name: greybox_transformation
version: '1.0'
profile: meltano
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]
model-paths:
- models
analysis-paths:
- analysis
test-paths:
- tests
seed-paths:
- data
macro-paths:
- macros
snapshot-paths:
- snapshots
target-path: ../.meltano/
log-path: logs
packages-install-path: dbt_packages
clean-targets:
- dbt_packages
- logs
# - ../.meltano/transformers/dbt/target

# Project-wide variables
vars:
  # Which school year begins Year 1 - important because the count starts at 4 and
  # not all debates are league debates that come with year designation. Used
  # primarily in base__debata.sql.
  first_school_year: '2000-04-25'
  # Which achievements do we want to return by default for the current year?
  current_school_year: 23


models:
  +persist_docs:
    relation: true
    columns: true
  greybox_transformation:
    base:
      +materialized: view
    achievements:
      +materialized: table
    final:
      +materialized: table
      +database: final
